[GLOBAL]
pants_version = "2.19.0"

backend_packages = [
  "pants.backend.docker",
  "pants.backend.docker.lint.hadolint",
  "pants.backend.python.lint.autoflake",
  "pants.backend.python",
  "pants.backend.python.lint.black",
  "pants.backend.python.lint.docformatter",
  "pants.backend.python.lint.flake8",
  "pants.backend.python.lint.isort",
  "pants.backend.python.typecheck.mypy",
  "pants.backend.shell",
  "pants.backend.shell.lint.shellcheck",
  "pants.backend.shell.lint.shfmt",
]

[anonymous-telemetry]
enabled = true
repo_id = "B573B56B-6289-40C5-ADB7-4C5FA659EAD1"


[python]
interpreter_constraints = ["==3.11.*"]

[python-infer]
use_rust_parser = true
